### ISSUE TITLE
A2L.xml Cruise Control, PTD Open-Degree Operation Switching Flag has duplicate unknown names

### ISSUE THREAD

**Issue by Asdow** [Pytrex/NissanDefinitions#10]
bit position 4 & 5 have the same name "Unknown 5 -" causing RomRaider to show only one of them, which makes it impossible to correctly change the bit flags.

Original:
`	<table type="BitwiseSwitch" name="Cruise Control, PTD Open-Degree Operation Switching Flag" category="Options//Flags" userlevel="1">
0x80		<bit position ="7" name="Unknown 7 -"/>   
0x40		<bit position ="6" name="mfPTDASCD - At the time of ASCD, PTD open-degree operation switching flag // Can't use for autos I don't think."/>
0x20		<bit position ="5" name="Unknown 5 -"/>  
0x10		<bit position ="4" name="Unknown 5 -"/>
0x08		<bit position ="3" name="Unknown 3 -"/>
0x04		<bit position ="2" name="Unknown 2 -"/>
0x02		<bit position ="1" name="Unknown 1 -"/>
0x01		<bit position ="0" name="Unknown 0 -"/>  
		<description>Toggle On/Off</description>
	</table>  
`

Fixed
`	<table type="BitwiseSwitch" name="Cruise Control, PTD Open-Degree Operation Switching Flag" category="Options//Flags" userlevel="1">
0x80		<bit position ="7" name="Unknown 7 -"/>   
0x40		<bit position ="6" name="mfPTDASCD - At the time of ASCD, PTD open-degree operation switching flag // Can't use for autos I don't think."/>
0x20		<bit position ="5" name="Unknown 5 -"/>  
0x10		<bit position ="4" name="Unknown 4 -"/>
0x08		<bit position ="3" name="Unknown 3 -"/>
0x04		<bit position ="2" name="Unknown 2 -"/>
0x02		<bit position ="1" name="Unknown 1 -"/>
0x01		<bit position ="0" name="Unknown 0 -"/>  
		<description>Toggle On/Off</description>
	</table>  
`

![original](https://user-images.githubusercontent.com/20314541/167312229-008a0877-c2cd-4b02-b604-6207075da06c.JPG)
![after fix](https://user-images.githubusercontent.com/20314541/167312234-6b502322-cd41-44b1-bf4c-05dc0eb0bd20.JPG)

**Comment by Pytrex** [comment]
Oooh good find! Thanks for bringing this up! I’ll include it with the BitwiseSwitch fix once I have time to complete that. Once again, thanks a ton! :)

**Comment by Pytrex** [comment]
Fixed in latest commit.
