### ISSUE TITLE
A2L.xml Fuel compensation transient acc/decel definitions incorrect size?

### ISSUE THREAD

**Issue by Asdow** [Pytrex/NissanDefinitions#12]
Comparing CF48D & CD415 in winols matches when mMITANDD & mMITANDA are interpreted as uint8[8][8], but they are uint8[16][16] in A2L.xml

Looking in Ghidra, the maps will overlap each other if the size is [16][16] instead of [8][8] which also shows up clearly in RomRaider
![asdra](https://user-images.githubusercontent.com/20314541/168425855-bb083b3b-ea3e-4719-911c-4dae448544c8.JPG)

**Comment by Pytrex** [comment]
Ahhh. I patched in extended map sizes for my personal ROM, so I must've forgotten to switch them back to their proper sizes when porting to the public repo. Thanks for finding this! It's fixed in the recent commit. :)
