### ISSUE TITLE
Added - AC610 definition

### ISSUE THREAD

**Issue by drbluetongue** [Pytrex/NissanDefinitions#21]
[AC610.zip](https://github.com/Pytrex/NissanDefinitions/files/11797440/AC610.zip)
[AC610.zip](https://github.com/Pytrex/NissanDefinitions/files/11797443/AC610.zip)

Hey mate

Turns out AC610 is 96% the same as AC510 so added the .xml (and the original .bin file) for you to add to your repository. 

Thanks a million for these definitions!

**Comment by Pytrex** [comment]
Fixed in #22 . But no problem!
